#:import dp kivy.metrics.dp

<BalanceScreen>:
    BoxLayout:
        orientation: "vertical"
        padding: dp(15)
        spacing: dp(12)
        canvas.before:
            Color:
                rgba: root.bg_color
            Rectangle:
                pos: self.pos
                size: self.size

        BoxLayout:
            size_hint_y: None
            height: dp(50)
            spacing: dp(10)

            Button:
                size_hint_x: None
                width: dp(46)
                background_normal: "Assets/back_arrow.png"
                background_down:   "Assets/back_arrow.png"
                background_color: root.icon_tint
                on_press: root.go_back()

            Label:
                text: "Budget Breakdown"
                bold: True
                font_size: "20sp"
                color: (1, 1, 1, 1)
                halign: "center"
                valign: "middle"
                text_size: self.size

            Widget:
                size_hint_x: None
                width: dp(46) 

        ScrollView:
            GridLayout:
                id: balance_list
                cols: 1
                spacing: dp(10)
                size_hint_y: None
                height: self.minimum_height
                padding: dp(4)
